# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7c0178484d11b24eb460532d3f04f5e0d60db4edf008f5f91d29176b5a59316c26574cae7f478965cf6d45cb92f617487ea184f334a6bf4454e227c757811d2

test:
  secret_key_base: d694329c34e1098198a51fc758491316dc7787d848f7f2744e1e38343137b9f0df924bb47fc6c3a2bc65ea1875a47b3175a5f5e50c525e9914f023e79a49102b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
